### ISSUE TITLE
Subsription specs vs programatically

### ISSUE THREAD

**Issue by adrianriobo** [adrianriobo/qe-eventmanager#15]
The idea is define subscription and actions based on yamls, initial idea would be something like:

```yaml
destinations:
  inTopic:
    topicName: topic1
    filters:
    - jsonpath: $.artifact.products[?(@.nvr=='codeready_containers-1')].nvr   
  outTopic: topic2
  errorTopic: topic3
actions:
  pipeline:
    name: pipeline-name
    params:
    - name: rhel-version
      jsonpath: $.artifact.products[(@.product=='rhel')].version
    results:
       event: event-name
       fields:
       - eventfieldName: event-name
         pipelineResultName: result-name
```

https://play.golang.com/p/Ewby5vYaVrn
https://golangrepo.com/repo/spyzhov-ajson-go-json

**Comment by adrianriobo** [comment]
new sample:

```yaml
consumerId: XXXXX
subscriptions:
  - destination: topic-XXX
    eventType: event-topic-XXX
    handlers:
    - name: interop
      filters:
      - $.artifact.products[?(@.nvr=='codeready_containers-1')].nvr
      - $.artifact.products[?(@.nvr=='openshift')].nvr
      pipeline:
          name: interop-ocp
          params:
          - name: rhel-version
            jsonpath: $.artifact.products[(@.product=='rhel')].id
      response:
        eventType: interop-ocp-testcomplete
        fields:
          - name: Category
            value: interoperability
          - name: Namespace
            value: interop
          - name: TestType
            value: product-scenario
          - name: Result
            pipelineResultName: resultStatus
          - name: Runtime
            pipelineResultName: duration
          - name: XunitUrls
            pipelineResultName: xunitURL
```
