### ISSUE TITLE
Create a configuration file structure

### ISSUE THREAD

**Issue by adrianriobo** [adrianriobo/qe-eventmanager#30]
```yaml
umb:
  consumerID: foo
  driver: amqp
  brokers: broker1:5556,broker2:5556
  userCertificate-data: XXXXXXX
  userKey-data: XXXXX
  certificateAuthority-data: XXXXXX
tekton:
  namespace: myNamespace
  workspaces:
  - name: workspace1
    pvc: pvc1
  - name: workspace2
    pvc: pvc2
  kubeconfig-data: XXXXXX #This value is optional, eventmanager can run based on RBAC inside the cluster
```
