### ISSUE TITLE
[Feature] Add optional action on input ack

### ISSUE THREAD

**Issue by adrianriobo** [adrianriobo/qe-eventmanager#38]
The idea would be define some action as an ack for input reception, sample

```yaml
name: gh-pr-updater
input: 
  umb: 
    topic: VirtualTopic.external.github.code-ready.crc
    filters:
    - $.action=='synchronize'
  ack:
    github:
      commitStatus:
        owner: XXXX
        repo: XXXX
        commit: XXXXX
        status: pending
```
